### ISSUE TITLE
Allow style props on components

### ISSUE THREAD

**Issue by Odonno** [Tropix126/fluent-svelte#21]
### Before you start...

- [X] Have you updated your dependencies? You might be using an old version of the library.
- [X] Have you checked if someone already requested this feature? If they have, post a comment with your use case instead.

### Description

Have you considered providing `style` prop on component so we can override CSS style the easy way?

**Comment by Tropix126** [comment]
Most components at the moment use the [$$restProps](https://svelte.dev/docs#template-syntax-attributes-and-props) feature of svelte, which passes all "unknown" props given to a component down to a specific element as HTML attributes. In fluent-svelte, the element these props are passed down to varies based on the component's functionality. In most cases, it's the outermost element of the rendered component.

So: in most cases you *can* actually use the `style` attribute to some extent. The problem here is that components are *not* a single element meant to be styled this way. Components are a complex tree of elements that render into an encapsulated UI pattern.

Rather than using this approach, a better method to style fluent-svelte components would be to use global styling + custom class names. At the moment almost *all* components have the option to provide a `class` prop, which will be applied to the outermost element in the component, meaning we can do something like this:

```html
<script>
	import { Button } from "fluent-svelte";
</script>

<Button class="custom-button">Button With Custom Styling</Button>

<style>
	:global(.custom-button) {
		padding: 20px;
	}
</style>
```

This is better for a few reasons:
1. It avoids the specificity hell you get into when using inline styles. The `style` attribute can only be overridden by an inline style below it or the `!important` flag.
2. You can still get scoped styles. `:global` in svelte essentially tells the compiler not to attach a hashed classname to a given piece of CSS, but you can also have something like `.container :global(.custom-button) {}` which will preserve a scope of `.container.svelte-<hash>`.
3. In general it avoids the confusion of where `{...$$restProps}` will be applied. Classes in fluent-svelte are *always* applied to the outermost given element.

**Comment by Tropix126** [comment]
If you have any other questions regarding styling limitations, feel free to ask me and i'd be glas to reopen this issue.

**Comment by Odonno** [comment]
@Tropix126 Yep, I get your point but I find style attribute to be quite useful sometime. Let's keep it that way and thank for the explanation about component styling.

Do you think it should be added in the docs?
